global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'jwt-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['jwt-service:8084']

  - job_name: 'produk-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['produk-service:8081']

  - job_name: 'pelanggan-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pelanggan-service:8082']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8083']